remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github: [metadata]
title: Laurestine Bradford
description: PhD Candidate, Linguistics, McGill University

exclude:
  - README.md
  - projects.md
